{% set version = "6.7.3" %}
{% set name = "Pyomo" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Pyomo/pyomo/archive/refs/tags/6.7.3.tar.gz
  sha256: d31cdd1c63a80d39e51ff79b1e9dc10a1a0814fafe7f68777e682129e2179614


build:
  number: 0
  script_env: PYOMO_SETUP_ARGS=--with-distributable-extensions
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - pyomo=pyomo.scripting.pyomo_main:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
    - pybind11

  run:
    - python
    - ply
    - pywin32  # [win]
  
  run_constrained:
    - matplotlib-base >=3.6.0,!=3.6.1
    - numpy <2.0.0

test:
  imports:
    - pyomo
    - pyomo.common
    - pyomo.common.collections
    - pyomo.contrib
    - pyomo.contrib.ampl_function_demo
    - pyomo.contrib.appsi
    - pyomo.contrib.appsi.cmodel
    - pyomo.contrib.appsi.examples
    - pyomo.contrib.appsi.solvers
    - pyomo.contrib.appsi.utils
    - pyomo.contrib.appsi.writers
    - pyomo.contrib.benders
    - pyomo.contrib.community_detection
    - pyomo.contrib.cp
    - pyomo.contrib.cp.repn
    - pyomo.contrib.cp.scheduling_expr
    - pyomo.contrib.cp.transform
    - pyomo.contrib.doe
    - pyomo.contrib.example
    - pyomo.contrib.example.plugins
    - pyomo.contrib.fbbt
    - pyomo.contrib.fme
    - pyomo.contrib.gdp_bounds
    - pyomo.contrib.gdpopt
    - pyomo.contrib.gjh
    - pyomo.contrib.iis
    - pyomo.contrib.incidence_analysis
    - pyomo.contrib.incidence_analysis.common
    - pyomo.contrib.interior_point
    - pyomo.contrib.interior_point.linalg
    - pyomo.contrib.mcpp
    - pyomo.contrib.mindtpy
    - pyomo.contrib.mpc
    - pyomo.contrib.mpc.data
    - pyomo.contrib.mpc.examples
    - pyomo.contrib.mpc.examples.cstr
    - pyomo.contrib.mpc.interfaces
    - pyomo.contrib.mpc.modeling
    - pyomo.contrib.multistart
    - pyomo.contrib.parmest
    - pyomo.contrib.parmest.examples
    - pyomo.contrib.parmest.examples.reaction_kinetics
    - pyomo.contrib.parmest.examples.reactor_design
    - pyomo.contrib.parmest.examples.rooney_biegler
    - pyomo.contrib.parmest.examples.semibatch
    - pyomo.contrib.parmest.utils
    - pyomo.contrib.piecewise
    - pyomo.contrib.piecewise.transform
    - pyomo.contrib.preprocessing
    - pyomo.contrib.preprocessing.plugins
    - pyomo.contrib.pynumero
    - pyomo.contrib.pynumero.algorithms
    - pyomo.contrib.pynumero.algorithms.solvers
    - pyomo.contrib.pynumero.examples
    - pyomo.contrib.pynumero.examples.callback
    - pyomo.contrib.pynumero.examples.external_grey_box
    - pyomo.contrib.pynumero.examples.external_grey_box.param_est
    - pyomo.contrib.pynumero.examples.external_grey_box.react_example
    - pyomo.contrib.pynumero.interfaces
    - pyomo.contrib.pynumero.linalg
    - pyomo.contrib.pynumero.sparse
    - pyomo.contrib.pyros
    - pyomo.contrib.satsolver
    - pyomo.contrib.sensitivity_toolbox
    - pyomo.contrib.sensitivity_toolbox.examples
    - pyomo.contrib.simplification
    - pyomo.contrib.simplification.ginac
    - pyomo.contrib.trustregion
    - pyomo.contrib.trustregion.examples
    - pyomo.contrib.viewer
    - pyomo.core
    - pyomo.core.base
    - pyomo.core.beta
    - pyomo.core.expr
    - pyomo.core.expr.calculus
    - pyomo.core.kernel
    - pyomo.core.kernel.piecewise_library
    - pyomo.core.plugins
    - pyomo.core.plugins.transform
    - pyomo.dae
    - pyomo.dae.plugins
    - pyomo.dataportal
    - pyomo.dataportal.plugins
    - pyomo.duality
    - pyomo.environ
    - pyomo.gdp
    - pyomo.gdp.plugins
    - pyomo.kernel
    - pyomo.mpec
    - pyomo.mpec.plugins
    - pyomo.neos
    - pyomo.neos.plugins
    - pyomo.network
    - pyomo.network.plugins
    - pyomo.opt
    - pyomo.opt.base
    - pyomo.opt.parallel
    - pyomo.opt.plugins
    - pyomo.opt.problem
    - pyomo.opt.results
    - pyomo.opt.solver
    - pyomo.repn
    - pyomo.repn.beta
    - pyomo.repn.plugins
    - pyomo.repn.plugins.ampl
    - pyomo.scripting
    - pyomo.scripting.plugins
    - pyomo.solvers
    - pyomo.solvers.plugins
    - pyomo.solvers.plugins.converter
    - pyomo.solvers.plugins.solvers
    - pyomo.util
    - pyomo.version
  source_files:
  # Tests are spread across many files throughout the source code.
    - .
  requires:
    - pip
    - pytest
    - parameterized
    - pybind11
    - distro
  commands:
    - pyomo --help
    - pip check
    {% set tests_to_skip = "abstract_ch_pyomo_buildactions_fails_sh" %}
    {% set tests_to_skip = tests_to_skip + " or abstract_ch_pyomo_model" %}
    {% set tests_to_skip = tests_to_skip + " or get_os_version" %}  # [linux]
    {% set tests_to_skip = tests_to_skip + " or test_expr5" %}  # [win]
    {% set tests_to_skip = tests_to_skip + " or test_construct" %}  # [win]
    {% set tests_to_skip = tests_to_skip + " or test_display" %}  # [win]
    {% set tests_to_skip = tests_to_skip + " or test_large_expression" %}  # [win]
    {% set tests_to_skip = tests_to_skip + " or test_pickle4" %}  # [win]
    {% set tests_to_skip = tests_to_skip + " or test_soln_pprint1" %}  # [win]
    {% set tests_to_skip = tests_to_skip + " or test_write_solution" %}  # [win]

    {% set tests_to_ignore = "--ignore=pyomo/solvers/tests/piecewise_linear/test_piecewise_linear_kernel.py" %}
    {% set tests_to_ignore = tests_to_ignore + " --ignore=pyomo/environ" %}
    {% set tests_to_ignore = tests_to_ignore + " --ignore=pyomo/repn/tests/mps/test_mps.py" %}  # [win]

    - pytest -k "not ({{ tests_to_skip }})" {{ tests_to_ignore }}

about:
  home: https://pyomo.org
  dev_url: https://github.com/Pyomo/pyomo
  doc_url: https://pyomo.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Python Optimization Modeling Objects
  description: |
    Pyomo is a Python-based open-source software package that supports a diverse set of
    optimization capabilities for formulating and analyzing optimization models. Pyomo 
    can be used to define symbolic problems, create concrete problem instances, and solve
    these instances with standard solvers.

extra:
  recipe-maintainers:
    - blnicho
    - jsiirola
    - mrmundt
    - whart222
