travis:
  secure:
    BINSTAR_TOKEN: bakBI3tpnkrKuvVjxtqVjj4TVE9HAVlpmYEqJFPcl72qPUU7p6Qua0cTd2DksMlkDkMfX0QGX3z4FPdKiNSVvktf/5KnhUjuatFBKc9o6jKB4nTkkXZ8MELwMlnH1OkilpsQaU/IkLMV5LI/fKhLzyatkMCtU9q9OBewYScJZOMaBjMqkA/VksR/WBhPEpQh7iSh/xGK1SPvNvA2PQXbpeqdwZ3sxgkYCn0PFCiLeQcQ22s2WXFO0ngfsohglF4MjqYin6IWORngyfGS7hQv6z9Gr3i1ghDB/3fojcxBzqJi7SgvnFWX5O01tHkk1O9HRZTq+NvGhfhS4bCyRHHsW0xjMxNE+QnRm9GYCHyK5KaJ/RdmrTTGqnAXH0xEj1zejjYkZpl0lt9lU1qphDdR4dvhyqUkH2fCb/5Vm7zuLB8uU+Paq+M6UowvYFInTWjOmA06ozcv5DNCgL8vY9F7TNEBnlxAZRIHLeGj1rjwOFCpTp+7+xABHtW36Mfpqn37KKKc0JwxZx5Fn+0sAW/vnBvsqU6CSTRCp30br+jjpOfgkKvrRoximX/G0nvxmiaGgLBJjxxyxGXtjqTUO8VnNek+VJUfobZ05GllILIFOirZ4tViGhIcSNvfg8nujnuKagSxpFBsT7Wnr2wUm4yLOaV/HKidFHuLkVNG4zAOGH4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
